[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_ETHEREUM_PROVIDER_URL='https://kovan.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://public-node.testnet.rsk.co'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER_URL='https://kovan.infura.io/v3/8886cb30669f45a19e3c42a0d81d7ebd'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
